---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: docker.io/library/redis:7.4.2@sha256:7f346df9cd82ade39512e2040acf3583e6af260b98c01fe525020bf89fb82783
          ports:
            - name: redis
              containerPort: 6379
