---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: romm
  namespace: romm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: romm
  template:
    metadata:
      labels:
        app: romm
    spec:
      containers:
        - name: romm
          image: docker.io/rommapp/romm:3.8.1@sha256:88b1717028a365ddb0fa4cb877679959ff78a5462b7c4a8edc15ff091c15c6b4
          startupProbe:
            httpGet:
              path: /api/heartbeat
              port: 8080
            failureThreshold: 5
            periodSeconds: 20
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: romm-data
              mountPath: /romm/assets
              subPath: assets/
            - name: romm-data
              mountPath: /romm/config
              subPath: config/
            - name: romm-data
              mountPath: /romm/resources
              subPath: resources/
            - name: romm-roms
              mountPath: /romm/library/roms
          envFrom:
            - configMapRef:
                name: romm
            - secretRef:
                name: romm
      volumes:
        - name: romm-data
          persistentVolumeClaim:
            claimName: romm-data
        - name: romm-roms
          persistentVolumeClaim:
            claimName: romm-roms
