---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: docker.io/library/postgres:14.17@sha256:7e3bebc13b6d0d79ee873b6ab1d0506dcabdbfd18157aa28bd2a9dc942da5e9d
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: postgres
              mountPath: /var/lib/postgresql/data
          envFrom:
            - secretRef:
                name: postgres
      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: postgres
