---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lidarr
  namespace: torrenting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      containers:
        - name: lidarr
          image: docker.io/linuxserver/lidarr:2.10.3@sha256:4c3d6942aa0ae3a7da5a4d6a59ee96e43777d834b4234f539bbb5d10a2db2900
          ports:
            - containerPort: 8686
          volumeMounts:
            - name: lidarr-config
              mountPath: /config
            - name: lidarr-downloads
              mountPath: /downloads
            - name: lidarr-music
              mountPath: /music
          envFrom:
            - configMapRef:
                name: lidarr-env
      volumes:
        - name: lidarr-config
          persistentVolumeClaim:
            claimName: lidarr-config
        - name: lidarr-downloads
          persistentVolumeClaim:
            claimName: lidarr-downloads
        - name: lidarr-music
          persistentVolumeClaim:
            claimName: lidarr-music
