---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: docker.io/library/postgres:14.17@sha256:a175d969e769f746d57376c82df58656f9c601367f755ec50c131e7c1a9f1bc9
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: postgres
              mountPath: /var/lib/postgresql/data
          envFrom:
            - secretRef:
                name: postgres
      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: postgres
