---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: docker.io/library/postgres:14.16@sha256:9d22683a87cb8ad297188af1d64993971107a70b0ca8852e493cd28285cf1d99
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: postgres
              mountPath: /var/lib/postgresql/data
          envFrom:
            - secretRef:
                name: postgres
      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: postgres
