---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: docker.io/library/nextcloud:30.0.6@sha256:c3314a96b8d286c9aa28566cc958d4ad8b520f3975d267bb091981cf4d7f040f
          ports:
            - name: web
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /status.php
              port: 80
            failureThreshold: 3
            periodSeconds: 5
          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/html
          envFrom:
            - configMapRef:
                name: nextcloud
            - secretRef:
                name: nextcloud
      volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-data
