---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: radarr
  namespace: torrenting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: docker.io/linuxserver/radarr:5.19.3@sha256:f68b553df8680cbbaa4bcb28c70dd322bf6ea86a35d7d5ba9b29f770f166e990
          ports:
            - containerPort: 7878
          volumeMounts:
            - name: radarr-config
              mountPath: /config
            - name: radarr-downloads
              mountPath: /downloads
            - name: radarr-movies
              mountPath: /movies
          envFrom:
            - configMapRef:
                name: radarr-env
      volumes:
        - name: radarr-config
          persistentVolumeClaim:
            claimName: radarr-config
        - name: radarr-downloads
          persistentVolumeClaim:
            claimName: radarr-downloads
        - name: radarr-movies
          persistentVolumeClaim:
            claimName: radarr-movies
