---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qbittorrent
  namespace: torrenting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: docker.io/linuxserver/qbittorrent:5.0.4@sha256:c3fad9933984990f7d8922706330fc301b93a8313b0e6764932bfba170e45618
          startupProbe:
            httpGet:
              path: /
              port: 8080
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: qbittorrent-config
              mountPath: /config
            - name: qbittorrent-downloads
              mountPath: /downloads
          envFrom:
            - configMapRef:
                name: qbittorrent
      volumes:
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-config
        - name: qbittorrent-downloads
          persistentVolumeClaim:
            claimName: qbittorrent-downloads
